{% set name = "pygraphml" %}
{% set version = "2.2" %}
{% set sha256 = "cbc3aedcf9b2d3c7c7c47c75182588b334ee3cb6ad0df047d2b368cdb0a8dd1b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - pygraphml

about:
  home: https://github.com/hadim/pygraphml/
  license: BSD 3-Clause
  summary: 'Small library to parse GraphML files in Python'
  license_family: BSD

extra:
  recipe-maintainers:
    - hadim
