context:
  name: pygraphml
  version: 2.4.2

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 65caafa0df6d32c46a6aff562748863f06b75fd8962c598b42fef84705615b3d

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - python >=3.6

tests:
  - python:
      imports:
        - pygraphml
      pip_check: false
  - requirements:
      run:
        - nose2
    script:
      - "python -c 'from pygraphml.tests import run_all; run_all()'"

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Small library to parse GraphML files in Python
  homepage: https://github.com/hadim/pygraphml/

extra:
  recipe-maintainers:
    - hadim
