travis:
  secure:
    BINSTAR_TOKEN: KbDh9AJQjuGnCwlqt0Nn2uIaYRlq31BwgOEUcRo2zaMDDj0/Q6AJ1AnZkryZfQ1zKcSNluYUTLAsmXvwQ2SqtCx7KDv9DSZAyOTUjbpNNvE8vwFdoSfC6cL+jZDEoRS5uWIsAqi43Jp/s/tdZJcJqwqtHVVug7COSV+CgKm2bhB53WUHywk8bgOxHRZB+lD70x4EAbp5zTt1Z01QNNkBXVsP1myuLrl1FtZS9Qm3zwvfJ3538oRb/BAzFKVG7k2zpBrjAnmE6eUNOoT+syxdUJ0kkbaIkZQC6NA4ybrYniVbN9XF7XqWAPGGjV7qgkfCJcURle5+mEjXixDlVaujWIDOvtGaaZ8KmwlaucdpCP7Wz/VXy+oPd92FfaabbzQNavm/GDyStUi2amefR4S7Qq/WN2F4cyhCAFcYlODhWsMDALYK3EofVm/LXEaDbjCt47Rmy5s9Da/yLZ8RTtEYXUkP87fhMDZOBfPaDE9T4wv7Z/ZL7pVV7iA3KGqdqpE2b2/2bOvtvVbwmuFg/nw0K762qhjXp1e53n7R3599nLS4tU4zhuulel2hJxC3D5HABwSdYAZuUYatOAqa+3r6LTciQGmy+7udMRY0rBg5zDPChMYkJLT9HODnYQwFcuwzFy/FA+gfcO3NbqUXt4Xv71u8/wl+etObzoK5UIzpjdE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
