travis:
  secure:
    BINSTAR_TOKEN: kjIO7CuL07wap4VoVSO8YLWvOqEw+rvYgqiBZkUyj5ElNFnaEVcTAjZeaS9nGzDV0JzyP9NRgiprYSn/xodQjCQXHtaElS/O7ciJutJ82TeeKvqfpg1ZkZv8w2ryrGxdn3n76AdU6FbRhOmOPppgqeBYM6Ra6BE5YIW3nzpaspXX15KTU2DHv5Bavilr2eXdUxCGbS0y/lklCbfWypiULKbX6k8OGrwPvSGmzsj1ERDTWDEJrJsTgpESVb9XF6A8XgjCGdONLTyyLLzw5rzYVyYkT0mJ+scbGJPqJN8WD33e1FeDeGmNgIIhK67VyRdmwgpdQ2lXzRdgsAbVaS1nDcYfnhUvKUOhA+9yRGZlErmWb1TRvYuVvzKLXdqAfXcfk4D0nzYUGFKKOlOHlu4hDLjNp/7RE3bsg1jaRHuKxR0OQitegaeZ9r5Jd3Nha+4mo+p0YcUjHyRTHSpKhdyhvbKQ2u+j4ORDqewk4URgIe32fOpz/ay8UdDOFO+wmqT7tH7JGixQz10rUeKq4ZKnn9UMCBON32VaL01Z125Ddjn6S7S1xUDPnVse+lsGIl3MztYTUww+NVdH3u0o49YkMVMJhcTXwPNWxmjed0OcRBLAPOdSlP0Fq1YczOyGrt201FtVqrsAaLSpzX9cMzekaQjimLcFMGvECh/4LEKCvYY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
